# Generated by Django 6.0.6 on 2026-06-11 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('brush_course', '刷课'), ('campus_run', '校园跑'), ('homework', '作业'), ('internship_proof', '实习证明'), ('thesis', '论文'), ('medical_record', '病历'), ('other', '其他')], max_length=50, verbose_name='服务项目')),
                ('username', models.CharField(max_length=100, verbose_name='账号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('course_name', models.CharField(blank=True, default='', max_length=200, verbose_name='课程名称')),
                ('times', models.IntegerField(blank=True, null=True, verbose_name='次数')),
                ('distance', models.CharField(blank=True, default='', max_length=50, verbose_name='距离(KM)')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('cost', models.IntegerField(default=0, verbose_name='消耗欢乐豆')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '服务订单',
                'verbose_name_plural': '服务订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joy_dots', models.IntegerField(default=0, verbose_name='欢乐豆')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户扩展',
                'verbose_name_plural': '用户扩展',
            },
        ),
    ]
