# Generated by Django 6.0.6 on 2026-06-11 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='cost',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='消耗欢乐豆'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='joy_dots',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='欢乐豆'),
        ),
    ]
